<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title></title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="/css/style.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script src="/js/app.js"></script>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <form id="searchForm">
            <input type="text" id="query" name="q">
            <select name="category" id="category">
                <option value="">Везде</option>
            </select>
            <button type="submit">Искать</button>
        </form>
    </body>
</html>
