<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title></title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="/css/style.css?<?= rand() ?>">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script src="/js/app.js?<?= rand() ?>"></script>
    </head>
    <body>
        <h1>FXTM</h1>
        <div>school store</div>

        <div class="wrapper">
            <form id="searchForm">
                <input type="text" id="query" name="q">
                <select name="category" id="category">
                    <option value="">In all Categories</option>
                    
                    <?php foreach ($categories as $item) : ?>
                        <option value="<?= $item->getId() ?>"><?= $item->getName() ?></option>
                    <?php endforeach; ?>

                </select>
                <button type="submit">Искать</button>
            </form>

            <div id="listItems">
            </div>

            <div id="editFormWrap">

            </div>
        </div>

    </body>
</html>
